export const pages = {
    LOGIN: 'LOGIN',
    PROFILE: 'PROFILE',
    NOTIFICATIONS: 'NOTIFICATIONS',
    INTEGRATIONS: 'INTEGRATIONS',
    SHARED_LINKS: 'SHARED_LINKS',
    MAIN_ASSETS: 'ASSETS',
    OVERVIEW: 'OVERVIEW',
    BILLING: 'BILLING',
    COMPANY: 'COMPANY',
    SECURITY: 'SECURITY',
    TEAM: 'TEAM',
    GUEST_UPLOAD: 'GUEST_UPLOAD',
    ATTRIBUTES: 'ATTRIBUTES',
    CUSTOM_SETTINGS: 'CUSTOM_SETTINGS',
    UPLOAD_APPROVAL: 'UPLOAD_APPROVAL'
}

export const events = {
    LOGOUT: 'LOGOUT',
    UPLOAD_ASSET: 'UPLOAD_ASSET', 
    SEARCH_ASSET:'SEARCH_ASSET',
    VIEW_ASSET: 'VIEW_ASSET',
    DOWNLOAD_ASSET: 'DOWNLOAD_ASSET',
    SHARE_ASSET: 'SHARE_ASSET',
    DOWNLOAD_COLLECTION: 'DOWNLOAD_COLLECTION',
    SHARE_COLLECTION:'SHARE_COLLECTION',
    DOWNLOAD_SHARED_ASSET: 'DOWNLOAD_SHARED_ASSET',
    VIEW_SHARED_ASSET: 'VIEW_SHARED_ASSET',
    ACCESS_SHARED_LINK: 'ACCESS_SHARED_LINK',
    VIEW_TAB: 'VIEW_TAB'
}