stages:
  - dev_build
build_dev:
 stage: dev_build
 before_script:
   - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
   - eval $(ssh-agent -s)
   - mkdir -p ~/.ssh
   - chmod 700 ~/.ssh
   - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
   - apt-get --yes --force-yes install rsync
   - echo $develop_key >>  develop_key
   - chmod 400 develop_key

 script:
   - rsync -avz -e 'ssh -o StrictHostKeyChecking=no -i develop_key' --stats --exclude-from=deployment-exclude-list.txt . $deveop_user@$develop_host:$develop_path_client;
   - ssh -o StrictHostKeyChecking=no -i develop_key -t $deveop_user@$develop_host -p 22 "cd $develop_path_client && npm install && npm run build && pm2 restart all"
 only:
   - dev