stages:
  - esdev_build
build_dev:
 stage: esdev_build
 before_script:
   - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
   - eval $(ssh-agent -s)
   - mkdir -p ~/.ssh
   - chmod 700 ~/.ssh
   - echo $develop_key >> develop_key
   - chmod 400 $develop_key
   - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
   - apt-get update -y
   - apt-get -y install rsync
 script:
   - ssh -i develop_key $develop_user@$develop_host
 only:
   - dev