stages:
  - esdev_build
build_dev:
 stage: esdev_build
 before_script:
   - apt-get update
   - apt-get --yes --force-yes install rsync
   - echo $develop_key >>  develop_key
   - chmod 400 develop_key
 script:
   - echo develop_key

 only:
   - dev