stages:
  - esdev_build
build_dev:
 stage: esdev_build
 before_script:
   - apt-get update
   - apt-get --yes --force-yes install rsync
   - apt-get --yes --force-yes install sshpass
   - mkdir "${HOME}/.ssh"
   - echo "${DEVELOP_PUBLIC_KEY}" > "${HOME}/.ssh/known_hosts"
   - echo "${DEVELOP_PRIVATE_KEY}" > "${HOME}/.ssh/id_rsa"
   - chmod 700 "${HOME}/.ssh/id_rsa"
 script:
   - rsync -hrvz -e "ssh -i ${HOME}/.ssh/id_rsa" . $deveop_user@$develop_host:$develop_path_client;
   - ssh -o StrictHostKeyChecking=no ${HOME}/.ssh/id_rsa -t $deveop_user@$develop_host -p 22 "cd $develop_path_client && npm install && npm run build && pm2 restart all"
 
 only:
   - dev