stages:
  - esdev_build
build_dev:
 stage: esdev_build
 before_script:
   - apt-get update
   - apt-get --yes --force-yes install rsync
   - apt-get --yes --force-yes install sshpass
   - echo $develop_key >>  develop_key.pem
   - chmod 400 develop_key.pem
 script:
   - rsync -avz -e 'sshpass -p "$develop_password" ssh -o StrictHostKeyChecking=no --stats --exclude-from=deployment-exclude-list.txt . $deveop_user@$develop_host:$develop_path_client;
   - ssh -o StrictHostKeyChecking=no -i develop_key.pem -t $deveop_user@$develop_host -p 22 "cd $develop_path_client && npm install && npm run build && pm2 restart all"
 
 only:
   - dev