stages:
  - develop_build
build_dev:
 stage: develop_build
 before_script:
    - mkdir -p ~/.ssh && chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - chmod 600 ${SSH_KEY}
    - export COMMIT_TIME=$(git show -s --format=%ct $CI_COMMIT_SHA)
 script:
   - apt-get update -y && apt-get install -y rsync
   - rsync -aHv --delete -e "ssh -i ${SSH_KEY} ${SSH_OPTS}" . ${deveop_user}@${develop_host}:${develop_path_client}
 only:
   - dev